name: get fit

on:
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: google-drive-download-action
        uses: raeperd/google-drive-download-action@v1
        with:
          clientId: ${{ secrets.CLIENTID }}
          clientSecret: ${{ secrets.CLIENTSECRET }}
          redirectUri: ${{ secrets.REDIRECTURI }}
          credential_json: ${{ secrets.CREDENTIALJSON }}
          q: "'1iWtlOyGYrmytsBogzuvh9W6IV2IqTolX' in parents"
          path: "./FIT_OUT"
