name: get fit

on:
  workflow_dispatch:

  runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: raeperd/raeperd/google-drive-download-action@v1.0
          with:
            clientId: ${{ secrets.CLIENT_ID }}
            clientSecret: ${{ secrets.CLIENT_SECRET }}
            redirectUri: ${{ secrets.REDIRECT_URI }}
            credential_json: ${{ secrets.CREDENTIAL_JSON }}
            q: "'1U-2NgagKTnqkIZrML52A2SsD9HDDeDN7' in parents"
            path: "./"
