name: Get FIT File

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Rclone action
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
    - run: |
        rclone ls "google drive":/HealthFit
        rclone copy "google drive":HealthFit ./FIT_OUT
