name: Get FIT File

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/static/*.json'
env:
  GITHUB_NAME: shaonianche
  GITHUB_EMAIL: github@duanfei.org

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rclone action
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
    - run: |
        rclone sync "google drive:/HealthFit" ./FIT_OUT --drive-formats '{"^(\d{4}-\d{2}-\d{2}-\d{6})\.fit": "{1}"}'
    - name: Push fit file
      run: |
        git config --local user.email '${{ env.GITHUB_EMAIL }}'
        git config --local user.name '${{ env.GITHUB_NAME }}'
        git add .
        git commit -a -m 'update fit file' || echo 'nothing to commit'
        git push || echo 'nothing to push'
