name: Get FIT File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
  push:
    branches:
      - main
     
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rclone action
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
    - run: |
        rclone sync "running-data-sync:/HealthFit" ./FIT_OUT --update
        
    - name: Rename file
      run: |
        cd ./FIT_OUT
        for file in *.fit; do
          new_name=$(echo "$file" | sed -E 's/^([0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6}).*\.fit$/\1.fit/')
          mv "$file" "$new_name"
        done
        cd ..

    - name: Push fit file
      run: |
          if git diff --quiet; then
              echo "No changes to commit"
              exit 0
          fi

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m 'update new runs'
          git pull --rebase --autostash origin ${{ github.ref }}
          git push
