name: Get FIT File

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Interact with Google Drive
        uses: satackey/action-google-drive@v1.2.1
        with:
          google-client-id: ${{ secrets.CLIENTID }}
          google-client-secret: ${{ secrets.CLIENTSECRET }}
          skicka-tokencache-json: ${{ secrets.CREDENTIAL_JSON }}
          download-from: "HealthFit"
          download-to: "./FIT_OUT"
