name: Get FIT File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
  push:
    branches:
      - main
     
permissions:
  contents: write

env:
  REMOTE_PATH: "running-data-sync:/HealthFit"
  LOCAL_PATH: "./FIT_OUT"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rclone action
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
    
    - name: Rclone sync    
      run: rclone sync "${{ env.REMOTE_PATH }}" "${{ env.LOCAL_PATH }}"  --update --checksum
        
    - name: Rename file
      run: |
        ls "${{ env.LOCAL_PATH }}"
        cd "${{ env.LOCAL_PATH }}"
        for file in *-*-*.fit; do
            if [[ $file =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6} ]]; then
                mv "$file" "${file:0:17}.fit"
            fi
        done
        cd ..

    - name: Push fit file
      run: |
          if git diff --quiet; then
              echo "No changes to commit"
              exit 0
          fi

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: sync and normalize FIT files $(date +'%Y-%m-%d %H:%M:%S')"
          git pull --rebase --autostash origin ${{ github.ref }}
          git push
