name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Add upstream remote 
      run: |
        git remote add upstream https://github.com/yihong0618/running_page
        git fetch upstream

    - name: Generate and apply patch
      run: |
        UPSTREAM_DIR="run_page/gpxtrackposter"
        LOCAL_DIR="scripts/gpxtrackposter"

        git diff upstream/master HEAD -- $UPSTREAM_DIR > changes.patch
        sed -i "s|a/$UPSTREAM_DIR|a/$LOCAL_DIR|g; s|b/$UPSTREAM_DIR|b/$LOCAL_DIR|g" changes.patch
        if git apply --check changes.patch; then
            git apply changes.patch
            git add $LOCAL_DIR
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git commit -m "Sync from upstream $UPSTREAM_DIR to $LOCAL_DIR"
        else
            echo "Patch failed to apply cleanly. Please resolve conflicts manually."
        exit 1
        fi